# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apelissi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/29 13:32:02 by apelissi          #+#    #+#              #
#    Updated: 2017/11/29 15:11:21 by apelissi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -o ft_display_file ft_display_file.c && gcc -c *.c

clean:
	rm -f *.o

fclean: clean
	rm ft_display_file
